name: Set Labels
description: Issue or PR title must follow conventional commits.

inputs:
    github-token:
        description: The GitHub token to use.
        required: true

runs:
    using: "composite"
    steps:
        - name: Set Labels
          uses: actions/github-script@v7
          with:
              github-token: ${{ inputs.github-token }}
              script: |
                  const { NUMBER, OWNER, REPO, TITLE } = process.env
                  const regex = /^(build|chore|ci|deps|docs|feat|fix|perf|refactor|revert|style|test)(?:\((\S+)\))?(!)?: (.+)$/;
                  const releaseRegex = /^chore\(\S*\): release/;

                  console.log(`Checking title "${TITLE}"`);
                  console.log("For more information: https://www.conventionalcommits.org/en/v1.0.0/");

                  if (!regex.test(TITLE)) {
                      throw new Error("Title must follow conventional commit format");
                  }

                  const labels = [];
                  const match = TITLE.match(regex);

                  switch (match[1]) {
                      case "feat":
                          labels.push("feature");
                          break;
                      default:
                          labels.push(match[1]);
                          break;
                  }

                  if (match[3]) {
                      labels.push("major");
                  }
                  else if (labels.includes("feature")) {
                      labels.push("minor");
                  }
                  else if (labels.includes("fix")) {
                      labels.push("patch");
                  }
                  else if (labels.includes("deps")) {
                      labels.push("patch");
                  }

                  if (releaseRegex.test(TITLE)) {
                      labels.push("autorelease: pending");
                  }

                  console.log(`@${OWNER}/${REPO}#${NUMBER}: Setting labels to ${labels}`);

                  await github.rest.issues.setLabels({
                    owner: OWNER,
                    repo: REPO,
                    issue_number: NUMBER,
                    labels
                  });
          env:
              NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
              OWNER: ${{ github.repository_owner }}
              REPO: ${{ github.event.repository.name }}
              TITLE: ${{ github.event.issue.title || github.event.pull_request.title }}
