name: Assign issues and PRs to project

on:
  issues:
    types: [opened, reopened]

  pull_request:
    types: [opened, reopened]

  workflow_call:
    inputs:
      project-id:
        default: 2
        description: Issues and PRs will be assigned to that project. Default to 2 (Hedia).
        required: false
        type: number

    secrets:
      ASSIGN_TO_PROJECT_TOKEN:
        description: Personal Access Token with "repo" and "project" permissions.
        required: true

jobs:
  project:
    runs-on: ubuntu-latest
    steps:

      - id: addItem
        name: Add to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/hedia-team/projects/${{inputs.project-id}}
          github-token: ${{ secrets.ASSIGN_TO_PROJECT_TOKEN }}

      - if: github.event_name == 'pull_request'
        name: Set status
        uses: hedia-team/titoportas_update-project-fields@v0.1.0
        with:
          project-url: https://github.com/orgs/hedia-team/projects/${{inputs.project-id}}
          github-token: ${{ secrets.ASSIGN_TO_PROJECT_TOKEN }}
          item-id: ${{ steps.addItem.outputs.itemId }}
          field-keys: Status
          field-values: In Progress
