name: Assign issues and PRs to project

on:
    issues:
        types:
            - opened
            - reopened

    pull_request:
        types:
            - opened
            - reopened

    workflow_call:
        inputs:
            project-id:
                default: 2
                description: Issues and PRs will be assigned to that project. Default to 2 (Hedia).
                required: false
                type: number

jobs:
    project:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - id: addItem
              name: Add to project
              uses: actions/add-to-project@v0.5.0
              with:
                  project-url: https://github.com/orgs/hedia-team/projects/${{ inputs.project-id || 2 }}
                  github-token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}

            - if: github.event_name == 'pull_request'
              name: Set status
              uses: hedia-team/titoportas_update-project-fields@v0.1.0
              with:
                  project-url: https://github.com/orgs/hedia-team/projects/${{ inputs.project-id || 2 }}
                  github-token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
                  item-id: ${{ steps.addItem.outputs.itemId }}
                  field-keys: Status
                  field-values: In Progress
