name: Build and Push Docker Image

on:
    workflow_call:
        inputs:
            tag_name:
                type: string
                description: Tag name
                required: false
                default: latest
        secrets:
            READONLY_NPM_TOKEN:
                description: Needed to install private @hedia npm packages
                required: true
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to push to GitHub Container Registry
                required: true

permissions:
    contents: write
    pull-requests: write
    packages: write

jobs:
    build-and-push-docker-image:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Create .npmrc
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.READONLY_NPM_TOKEN }}" > .npmrc

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository }}:${{ inputs.tag_name }}
                      ghcr.io/${{ github.repository }}:latest
