name: Bulk Release Please

on:
    workflow_dispatch:
        inputs:
            topic:
                type: choice
                description: Target repositories with topic
                required: true
                default: service
                options:
                    - app
                    - backend
                    - dev
                    - io
                    - module
                    - org
                    - platform
                    - runtime
                    - service
                    - test

jobs:
    bulk-release-please:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Bulk Release Please
              run: |
                  urls=$(gh repo list hedia-team --limit 1000 --topic=${{ inputs.topic }} --no-archived --json=url --jq=".[] | .url")

                  echo "Running Release Please for the following repos:"

                  for url in $urls
                  do
                    echo "* $url"
                    gh workflow run --repo $url release-please.yml || true
                  done

                  echo " "
                  echo "Well done! You seem to have a lot on your plate now... Let's get to work!"
              env:
                  GH_TOKEN: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
