name: CI Please
on:
    workflow_call:
        inputs:
            build:
                description: Build
                type: boolean
                required: false
                default: false

            docker:
                description: Docker
                type: boolean
                required: false
                default: false

            e2e:
                description: E2E
                type: boolean
                required: false
                default: false

            eslint:
                description: ESLint
                type: boolean
                required: false
                default: false

            package-lint:
                description: Package Lint
                type: boolean
                required: false
                default: false

            prettier:
                description: Prettier
                type: boolean
                required: false
                default: false

            sonar:
                description: Sonar
                type: boolean
                required: false
                default: false

            test:
                description: Test
                type: boolean
                required: false
                default: false

        secrets:
            READONLY_NPM_TOKEN:
                description: Needed to install private @hedia npm packages
                required: true
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to push to GitHub Container Registry
                required: true

permissions:
    contents: write
    pull-requests: write
    packages: write

jobs:
    build:
        if: ${{ inputs.build == 'true' }}
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/build-please.yml@feat-docker-please-with-ref

    docker:
        if: ${{ inputs.docker == 'true' }}
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/docker-please.yml@feat-docker-please-with-ref

    e2e:
        if: ${{ inputs.e2e == 'true' }}
        uses: hedia-team/e2e-service/.github/workflows/test-please.yml@feat-docker-please-with-ref
        secrets: inherit
        with:
            package-name: ${{ github.event.repository.name }}
            package-tag: ${{ github.ref }}
            suite: "All"

    eslint:
        if: ${{ inputs.eslint == 'true' }}
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/eslint-please.yml@feat-docker-please-with-ref

    package-lint:
        if: ${{ inputs.package-lint == 'true' }}
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/package-lint-please.yml@feat-docker-please-with-ref

    prettier:
        if: ${{ inputs.prettier == 'true' }}
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/prettier-please.yml@feat-docker-please-with-ref

    sonar:
        if: ${{ inputs.sonar == 'true' }}
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/sonar-please.yml@feat-docker-please-with-ref

    test:
        if: ${{ inputs.test == 'true' }}
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/ci-test.yml@feat-docker-please-with-ref
