name: Prettier

on:
    workflow_call:
        secrets:
            READONLY_NPM_TOKEN:
                description: Needed to install private @hedia npm packages
                required: true

jobs:
    prettier:
        runs-on: ${{ vars.CI_PRETTIER_RUNNER }}
        timeout-minutes: 5

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js Environment
              uses: actions/setup-node@v4
              with:
                  always-auth: true
                  cache: "npm"
                  node-version-file: package.json
                  registry-url: https://registry.npmjs.org
                  scope: "@hedia"

            - name: Install Dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READONLY_NPM_TOKEN }}

            - name: Run Prettier
              run: npm run prettier:check
