name: Deploy Please

on:
    workflow_call:
        inputs:
            apps:
                type: string
                description: A comma-separated list of Scalingo apps to deploy. For example, "hedia-com-foo,hedia-dev-foo".
                required: true
            version:
                type: string
                description: The release version to deploy. For example, "v1.0.0". Default to the greatest version. If a release triggered the workflow, its tag will be used.
                required: false

        secrets:
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to deploy to Scalingo
                required: true
            SCALINGO_TOKEN:
                description: Needed to deploy to Scalingo
                required: true

jobs:
    deploy-please:
        if: github.event_name != 'release' || endsWith(github.ref_name, '.0.0') == false
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - id: version
              name: Select Version
              run: |
                  if [[ -n "$INPUT" ]]; then
                    VERSION="$INPUT"
                  elif [[ -n "$RELEASE" ]]; then
                    VERSION="$RELEASE"
                  else
                    VERSION="$(git tag | grep --regexp='^v[0-9]' | sort --version-sort | tail -1)"
                  fi
                  echo "version=$VERSION" >> $GITHUB_OUTPUT
              env:
                  INPUT: ${{ inputs.version }}
                  RELEASE: ${{ github.event_name == 'release' && github.ref_name }}

            - name: Download the Release
              run: gh release download ${{ steps.version.outputs.version }} --archive=tar.gz
              env:
                  GH_TOKEN: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}

            - name: Setup Scalingo CLI
              run: |
                  curl -O https://cli-dl.scalingo.com/install &&
                  bash install &&
                  scalingo login --api-token ${{ secrets.SCALINGO_TOKEN }}

            - name: Deploy to Scalingo
              run: |
                  for app in ${APPS//,/ }
                  do
                    scalingo --app $app deploy --no-follow "${REPO}-${VERSION:1}.tar.gz" $VERSION
                  done
              env:
                  APPS: ${{ inputs.apps }}
                  REPO: ${{ github.event.repository.name }}
                  VERSION: ${{ steps.version.outputs.version }}
