name: Dockerize Please

on:
    workflow_call:
        inputs:
            github_ref:
                description: The git ref to check out; will use the tag_name if not provided
                type: string
                required: false
            tag_name:
                type: string
                description: The tag to use for the Docker image
                required: false

        secrets:
            READONLY_NPM_TOKEN:
                description: Needed to install private @hedia npm packages
                required: true
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to push to GitHub Container Registry
                required: true

permissions:
    contents: write
    pull-requests: write
    packages: write

jobs:
    dockerize-please:
        runs-on: ${{ vars.DOCKERIZE_PLEASE_RUNNER }}
        timeout-minutes: 10
        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.github_ref || inputs.tag_name }}

            - name: Create .npmrc
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.READONLY_NPM_TOKEN }}" > .npmrc

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}

            - name: Build and push Docker image (Ref)
              if: ${{ inputs.github_ref }}
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository }}:${{ inputs.github_ref }}

            - name: Build and push Docker image (Tag and Latest)
              if: ${{ inputs.tag_name }}
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository }}:${{ inputs.tag_name }}
                      ghcr.io/${{ github.repository }}:latest

            - name: Initiate E2E test workflow
              if: ${{ inputs.tag_name }}
              run: |
                  gh workflow run --repo hedia-team/e2e-service --raw-field suite="All" test-please.yml
              env:
                  GH_TOKEN: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
