name: E2E Please

on:
    workflow_call:
        inputs:
            package-name:
                type: string
                description: The Package Name
                required: true
            package-tag:
                type: string
                description: The Package Tag
                required: true

        secrets:
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to push to GitHub Container Registry
                required: true

permissions:
    contents: write
    pull-requests: write
    packages: write

jobs:
    dockerize-please:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Run E2E Test Workflow
              run: |
                  gh workflow run --repo hedia-team/e2e-service --raw-field suite="All" --raw-field package-name=${{ inputs.package-name }} --raw-field package-tag=${{ inputs.package-tag }} test-please.yml
              env:
                  GH_TOKEN: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
