name: E2E Please

on:
    workflow_call:
        inputs:
            service-name:
                type: string
                description: The Tag to use for the Developer Service Docker image
                required: false
            service-tag:
                type: string
                description: The Tag to use for the Developer Service Docker image
                required: false

        secrets:
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to push to GitHub Container Registry
                required: true

permissions:
    contents: write
    pull-requests: write
    packages: write

jobs:
    dockerize-please:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Run E2E Test Workflow
              run: |
                  gh workflow run --repo hedia-team/e2e-service --raw-field suite="All" --raw-field service-name=${{ inputs.service-name }} --raw-field service-tag=${{ inputs.service-tag }} test-please.yml
              env:
                  GH_TOKEN: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
