name: Issue

on:
    issues:
        types:
            - edited
            - opened
            - reopened

    workflow_call:
        inputs:
            project-id:
                description: The issue will be assigned to that project.
                required: true
                type: number

jobs:
    issue:
        runs-on: ubuntu-latest
        steps:
            - name: Link Project
              uses: actions/add-to-project@releases/v1
              with:
                  github-token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
                  project-url: https://github.com/orgs/hedia-team/projects/${{ github.event.inputs.project-id || 2 }}

            - name: Set Labels
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
                  script: |
                      const owner = "${{github.repository_owner}}";
                      const repo = "${{github.event.repository.name}}";
                      const issue_number = ${{github.event.issue.number}};
                      const title = "${{github.event.issue.title}}";
                      const regex = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(?:\((\w+)\))?(!)?: (.+)$/;

                      console.log(`Checking title "${title}"`);
                      console.log("For more information: https://www.conventionalcommits.org/en/v1.0.0/");

                      if (!regex.test(title)) {
                          throw new Error("Title must follow conventional commit format");
                      }

                      const labels = [];
                      const match = title.match(regex);

                      switch (match[1]) {
                          case "feat":
                              labels.push("feature");
                              break;
                          default:
                              labels.push(match[1]);
                              break;
                      }

                      if (match[3]) {
                          labels.push("major");
                      }
                      else if (labels.includes("feature")) {
                          labels.push("minor");
                      }
                      else {
                          labels.push("patch");
                      }

                      console.log(`@${owner}/${repo}#${issue_number}: Setting labels to ${labels}`);

                      await github.rest.issues.setLabels({ owner, repo, issue_number, labels });
