name: Issue

on:
    issues:
        types:
            - edited
            - opened
            - reopened

    workflow_call:

jobs:
    issue:
        runs-on: ubuntu-latest
        steps:
            - name: Link Project
              uses: actions/add-to-project@releases/v1
              with:
                  github-token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
                  project-url: https://github.com/orgs/hedia-team/projects/2

            - name: Set Labels
              uses: hedia-team/.github/.github/actions/set-labels@big-refactor
              with:
                  github-token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
