name: npm-package-json-lint Please

on:
    workflow_call:
        secrets:
            READONLY_NPM_TOKEN:
                description: Needed to install private @hedia npm packages
                required: true

jobs:
    run:
        runs-on: ${{ vars.NPM_PACKAGE_JSON_LINT_RUNNER }}
        timeout-minutes: 1

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js Environment
              uses: actions/setup-node@v4
              with:
                  always-auth: true
                  cache: "npm"
                  node-version-file: package.json
                  registry-url: https://registry.npmjs.org
                  scope: "@hedia"

            - name: Install Dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READONLY_NPM_TOKEN }}

            - name: Run Package Lint
              run: npm run package:lint
