name: Publish Please

on:
    workflow_call:
        inputs:
            github_ref:
                description: The git ref to publish
                type: string
                required: true

        secrets:
            READONLY_NPM_TOKEN:
                description: Needed to install private @hedia npm packages
                required: true
            PUBLISHING_NPM_TOKEN:
                description: Needed to publish @hedia npm packages
                required: true

jobs:
    publish-please:
        runs-on: ${{ vars.PUBLISH_PLEASE_RUNNER }}
        timeout-minutes: 5
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.github_ref }}

            - name: Setup Node.js Environment
              uses: actions/setup-node@v4
              with:
                  node-version-file: "package.json"
                  always-auth: true
                  registry-url: https://registry.npmjs.org
                  scope: "@hedia"

            - name: Install Dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READONLY_NPM_TOKEN }}

            - name: Build
              run: npm run build --if-present

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PUBLISHING_NPM_TOKEN }}
