name: Release Please

on:
    workflow_call:
        outputs:
            release_created:
                description: "Whether or not a release was created"
                value: ${{ jobs.release-please.outputs.release_created }}
            tag_name:
                description: "The tag name (version number) of the release created"
                value: ${{ jobs.release-please.outputs.tag_name }}

        secrets:
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to run release-please
                required: true

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        if: >
            github.event_name == 'workflow_dispatch' ||
            (
              github.event_name == 'pull_request' &&
              github.event.pull_request.merged == true &&
              contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
            )
        steps:
            - name: Fetch release-please configuration
              run: |
                curl -o .github/release-please-config.json https://raw.githubusercontent.com/hedia-team/.github/enable-deps-as-release/release-please-config.json

            - id: release-please
              name: Release Please
              uses: googleapis/release-please-action@v4
              with:
                  release-type: node
                  token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
                  target-branch: ${{ github.ref_name }}
                  config-file: ".github/release-please-config.json"
        outputs:
            release_created: ${{ steps.release-please.outputs.release_created }}
            tag_name: ${{ steps.release-please.outputs.tag_name }}
