name: Release Please

on:
    workflow_call:
        inputs:
            test-reports:
                description: Whether or not to run tests that produce reports to be uploaded to the release. Default to true
                required: false
                default: true
                type: boolean
            postgres:
                description: Database used in this workflow. Default to none
                required: false
                type: string
            rabbitmq:
                description: Whether or not to use RabbitMQ in this workflow. Default to false
                required: false
                default: false
                type: boolean
            redis:
                description: Whether or not to use Redis in this workflow. Default to false
                required: false
                default: false
                type: boolean
            version:
                description: Specific version number to release, eg '3.0.0' or '3.1.0-rc.0'. If not provided, Release Please will determine the version.
                required: false
                type: string

        outputs:
            release_created:
                description: "Whether or not a release was created"
                value: ${{ jobs.release-please.outputs.release_created }}
            tag_name:
                description: "The tag name (version number) of the release created"
                value: ${{ jobs.release-please.outputs.tag_name }}

        secrets:
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to run release-please
                required: true

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ${{ vars.RELEASE_PLEASE_RUNNER }}
        timeout-minutes: 5
        if: >
            github.event_name == 'workflow_dispatch' ||
            (
              github.event_name == 'pull_request' &&
              github.event.pull_request.merged == true &&
              contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
            )
        steps:
            - id: release-please
              name: Release Please
              uses: googleapis/release-please-action@v3
              with:
                  release-type: node
                  token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
                  default-branch: ${{ github.ref_name }}
                  changelog-types: '[{"type":"feat","section":"New Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"revert","section":"Reverted Changes","hidden":false},{"type":"perf","section":"Performance Improvements","hidden":false},{"type":"refactor","section":"Code Refactoring","hidden":false},{"type":"build","section":"Build Process","hidden":false},{"type":"ci","section":"CI/CD","hidden":false},{"type":"test","section":"Testing","hidden":false},{"type":"chore","section":"Chores","hidden":false},{"type":"docs","section":"Documentation Updates","hidden":false},{"type":"style","section":"Code Formatting","hidden":false}]'
                  release-as: ${{ inputs.version || '' }}

        outputs:
            release_created: ${{ steps.release-please.outputs.release_created }}
            tag_name: ${{ steps.release-please.outputs.tag_name }}

    build:
        if: ${{ needs.release-please.outputs.release_created && inputs.test-reports }}
        needs: release-please
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/ci-typescript.yml@latest

    test:
        needs: build
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/ci-test.yml@latest
        with:
            postgres: ${{ inputs.postgres }}
            rabbitmq: ${{ inputs.rabbitmq }}
            redis: ${{ inputs.redis }}

    attach-test-report-to-release:
        needs:
            - release-please
            - test
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Download reports
              uses: actions/download-artifact@v4
              with:
                  path: .
                  pattern: reports

            - name: Upload reports to release
              run: gh release upload ${{ needs.release-please.outputs.tag_name }} reports/*
              env:
                  GH_TOKEN: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
