name: Release Please

on:
    workflow_dispatch:
    pull_request:
        types: [closed]
        branches: [master, main]

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        if: >
            github.event_name == 'workflow_dispatch' ||
            (github.event_name == 'pull_request' &&
              github.event.pull_request.merged == true &&
              contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
            )
        steps:
            - uses: google-github-actions/release-please-action@v3
              with:
                  release-type: node
