name: Release Please

on:
    workflow_call:
        outputs:
            release_created:
                description: "Whether or not a release was created"
                value: ${{ jobs.release-please.outputs.release_created }}
            tag_name:
                description: "The tag name (version number) of the release created"
                value: ${{ jobs.release-please.outputs.tag_name }}

        secrets:
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to run release-please
                required: true

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        if: >
            github.event_name == 'workflow_dispatch' ||
            (
              github.event_name == 'pull_request' &&
              github.event.pull_request.merged == true &&
              contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
            )
        steps:
            - id: release-please
              name: Release Please
              uses: googleapis/release-please-action@v3
              with:
                  release-type: node
                  token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
                  default-branch: ${{ github.ref_name }}
                  changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"deps","section":"Dependencies","hidden":false}]'

        outputs:
            release_created: ${{ steps.release-please.outputs.release_created }}
            tag_name: ${{ steps.release-please.outputs.tag_name }}

    build:
        if: ${{ needs.release-please.outputs.release_created }}
        needs: release-please
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/ci-typescript.yml@latest

    test:
        needs: build
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/ci-test.yml@test-report

    attach-test-report-to-release:
        needs:
            - release-please
            - test
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Download reports
              uses: actions/download-artifact@v4
              with:
                  path: .
                  pattern: reports

            - name: Upload reports to release
              run: gh release upload ${{ needs.release-please.outputs.tag_name }} reports
              env:
                  GH_TOKEN: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
