name: Release and Publish

on:
    workflow_call:

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        uses: hedia-team/.github/.github/workflows/release-please.yml@latest

    publish:
        needs: release
        if: needs.release.outputs.release_created == 'true'
        uses: hedia-team/.github/.github/workflows/publish-please.yml@latest
        secrets: inherit
        with:
            github_ref: ${{ github.ref }}
