name: Release Please

on:
    workflow_call:
        inputs:
            reviewers:
                type: string
                description: A comma-separated list of reviewers (GitHub usernames) to request a review from.
                required: false
            team-reviewers:
                type: string
                description: A comma-separated list of GitHub teams to request a review from.
                required: false
        outputs:
            release_created:
                description: "Whether or not a release was created"
                value: ${{ jobs.release-please.outputs.release_created }}
            tag_name:
                description: "The tag name (version number) of the release created"
                value: ${{ jobs.release-please.outputs.tag_name }}
        secrets:
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to run release-please
                required: true

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        if: >
            github.event_name == 'workflow_dispatch' ||
            (github.event_name == 'pull_request' &&
              github.event.pull_request.merged == true &&
              contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
            )
        steps:
            - uses: googleapis/release-please-action@v4
              id: release-please
              with:
                  release-type: node
                  token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
                  target-branch: ${{ github.ref_name }}
        outputs:
            pr_number: ${{steps.release-please.outputs}}
            prs_created: ${{steps.release-please.outputs.prs_created}}
            release_created: ${{ steps.release-please.outputs.release_created }}
            tag_name: ${{ steps.release-please.outputs.tag_name }}
    assign-please:
        runs-on: ubuntu-latest
        needs: release-please
        steps:
            - uses: actions/github-script@v6
              with:
                  script: |
                      console.log("${{needs.release-please.outputs.pr_number}}");

                      if (${{needs.release-please.outputs.prs_created}}) {
                          const owner = "${{github.repository_owner}}";
                          const repo = "${{github.event.repository.name}}";
                          const pull_number = "${{needs.release-please.outputs.pr_number}}";
                          const assignees = [ "${{github.actor}}" ];
                          const reviewers = "${{inputs.reviewers}}".split(',').filter((reviewer) => reviewer);
                          const team_reviewers = "${{inputs.team-reviewers}}".split(',').filter((reviewer) => reviewer);

                          console.log(owner, repo, pull_number, assignees, reviewers, team_reviewers)

                          await github.rest.issues.addAssignees({ owner, repo, pull_number, assignees });
                          await github.rest.pulls.requestReviewers({ owner, repo, pull_number, reviewers, team_reviewers });
                      }
