name: Release Please

on:
    workflow_call:
        outputs:
            release_created:
                description: "Whether or not a release was created"
                value: ${{ jobs.release-please.outputs.release_created }}

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        if: >
            github.event_name == 'workflow_dispatch' ||
            (github.event_name == 'pull_request' &&
              github.event.pull_request.merged == true &&
              contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
            )
        steps:
            - uses: google-github-actions/release-please-action@v3
              id: release-please
              with:
                  release-type: node
        outputs:
            release_created: ${{ steps.release-please.outputs.release_created }}
