name: Release and Publish

on:
    workflow_call:

permissions:
    contents: write
    pull-requests: write

jobs:
    release-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Release Please
              uses: hedia-team/.github/.github/workflows/release-please.yml@latest
              id: release

            - name: Publish Please
              if: steps.release.outputs.release_created == 'true'
              uses: hedia-team/.github/.github/workflows/publish-please.yml@latest
              with:
                  github_ref: ${{ github.ref }}
