name: Self Release Please

on:
    pull_request:
        branches:
            - main
        types:
            - closed

    workflow_dispatch:

jobs:
    release-please:
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/release-please.yml@latest
        with:
            test-reports: false
