name: Pull Request

on:
    pull_request:
        types:
            - converted_to_draft
            - edited
            - opened
            - ready_for_review
            - reopened
            - review_requested
            - synchronize

jobs:
    pull-request:
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/pull-request.yml@latest
        with:
            team-reviewers: backend
