name: Continuous Integration

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened

    push:
        branches:
            - main

jobs:
    format:
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/ci-prettier.yml@latest

    package:
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/ci-package-lint.yml@latest
