name: Self Release Please

on:
    pull_request:
        branches:
            - main
            - release*
        types:
            - closed

    workflow_dispatch:
        inputs:
            version:
                description: Specific version number to release, eg '3.0.0' or '3.1.0-rc.0'. If not provided, Release Please will determine the version.
                required: false

jobs:
    release-please:
        secrets: inherit
        uses: hedia-team/.github/.github/workflows/release-please.yml@latest
        with:
            test-reports: false
            version: ${{ github.event.inputs.version || '' }}
