name: Update Please

on:
    workflow_call:
        inputs:
            target:
                type: string
                description: Target versions to upgrade to. For example, "latest", "minor" or "patch".
                default: minor

        secrets:
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to create the PR
                required: true
            READONLY_NPM_TOKEN:
                description: Needed to access private @hedia npm packages
                required: true

permissions:
    contents: write
    pull-requests: write

jobs:
    update-please:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref_name }}
                  token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}

            - name: Setup Node.js Environment
              uses: actions/setup-node@v4
              with:
                  always-auth: true
                  cache: "npm"
                  node-version-file: package.json
                  registry-url: https://registry.npmjs.org
                  scope: "@hedia"

            - name: Install npm-check-updates
              run: npm install -g npm-check-updates

            - name: Update ${{ inputs.target || 'minor' }} dependencies
              run: ncu -t ${{ inputs.target || 'minor' }} -u --install always
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READONLY_NPM_TOKEN }}

            - id: create-pull-request
              name: Create Pull Request
              uses: hedia-team/.github/.github/actions/create-pull-request@big-refactor
              with:
                  auto-merge: true
                  base: ${{ github.ref_name }}
                  body: "Update Please has found one or more dependencies to be updated! 🚀"
                  force: true
                  github-token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
                  head: "update-please-${{ github.sha }}"
                  title: "chore(deps): update dependencies"

            - name: Assign Actor
              run: gh pr edit --add-assignee ${{ github.event_name == 'workflow_dispatch' && github.actor || 'hedia-bot' }}
              env:
                  GH_TOKEN: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
