name: Update Please

on:
    workflow_call:
        inputs:
            reviewers:
                type: string
                description: A comma-separated list of reviewers (GitHub usernames) to request a review from.
                required: false
            team-reviewers:
                type: string
                description: A comma-separated list of GitHub teams to request a review from.
                required: false
            target:
                type: string
                description: Target versions to upgrade to. For example, "latest", "minor" or "patch".
                default: minor
        secrets:
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to create the PR
                required: true
            READONLY_NPM_TOKEN:
                description: Needed to access private @hedia npm packages
                required: true

permissions:
    contents: write
    pull-requests: write

jobs:
    update-please:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Setup Node.js Environment
              uses: actions/setup-node@v4
              with:
                  always-auth: true
                  cache: "npm"
                  node-version-file: package.json
                  registry-url: https://registry.npmjs.org
                  scope: "@hedia"

            - name: Install npm-check-updates
              run: npm install -g npm-check-updates

            - name: Update ${{ inputs.target }} dependencies
              run: ncu -t ${{ inputs.target }} -u
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READONLY_NPM_TOKEN }}

            - name: Install updated dependencies
              run: npm install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READONLY_NPM_TOKEN }}

            - name: Create Pull Request
              uses: hedia-team/create-pull-request@v6
              with:
                  token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
                  commit-message: "chore(deps): update dependencies"
                  title: "chore(deps): update dependencies"
                  body: "Update Please has found one or more dependencies to be updated! 🚀"
                  branch: update-please-${{ github.sha }}
                  labels: chore
                  reviewers: ${{ inputs.reviewers }}
                  team-reviewers: ${{ inputs.team-reviewers }}
