name: Update Please

on:
    workflow_call:
        inputs:
            target:
                type: string
                description: Target versions to upgrade to. For example, "latest", "minor" or "patch".
                default: minor

        secrets:
            HEDIA_BOT_GITHUB_PAT:
                description: Needed to create the PR
                required: true
            READONLY_NPM_TOKEN:
                description: Needed to access private @hedia npm packages
                required: true

permissions:
    contents: write
    pull-requests: write

jobs:
    update-please:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}

            - name: Setup Node.js Environment
              uses: actions/setup-node@v4
              with:
                  always-auth: true
                  cache: "npm"
                  node-version-file: package.json
                  registry-url: https://registry.npmjs.org
                  scope: "@hedia"

            - name: Install npm-check-updates
              run: npm install -g npm-check-updates

            - name: Checkout Branch
              run: git checkout -b update-please-${{ github.sha }}

            - name: Update ${{ inputs.target || 'minor' }} dependencies
              run: ncu -t ${{ inputs.target || 'minor' }} -u --install always
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READONLY_NPM_TOKEN }}

            - id: check-dependencies
              name: Check if dependencies are up-to-date
              run: "[[ -n $(git status --porcelain) ]] && echo 'up-to-date=false' >> $GITHUB_OUTPUT || echo 'up-to-date=true' >> $GITHUB_OUTPUT"

            - if: steps.check-dependencies.outputs.up-to-date == 'false'
              name: Commit Changes
              run: |
                  git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
                  git config user.name ${{ github.actor }}
                  git add .
                  git commit -m "chore(deps): update dependencies"
                  git push -u origin update-please-${{ github.sha }}

            - if: steps.check-dependencies.outputs.up-to-date == 'false'
              id: create-pull-request
              name: Create Pull Request
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
                  script: |
                      const owner = "${{ github.repository_owner }}";
                      const repo = "${{ github.event.repository.name }}";
                      const head = "update-please-${{ github.sha }}";
                      const base = "main";
                      const title = "chore(deps): update dependencies";
                      const body = "Update Please has found one or more dependencies to be updated! 🚀";

                      const { data } = await github.rest.pulls.create({ owner, repo, head, base, title, body });

                      console.log(`@${owner}/${repo}#${data.number}: PR Created`);

                      return { pull_number: data.number };

            - if: steps.check-dependencies.outputs.up-to-date == 'false'
              name: Enable Auto-Merge
              run: gh pr merge ${{ steps.create-pull-request.outputs.result.pull_number }} --auto --squash --repo ${{ github.repository }}
              env:
                  GH_TOKEN: ${{ secrets.HEDIA_BOT_GITHUB_PAT }}
